Repository gpuweb/gpuweb, pull requests merged in 2022-10, with the labels that each got.

#3482 Clarify definition of the concretization of a type.
  wgsl/index.bs
Labels: editorial, wgsl:types

#3488 Fix for two README typos
  wgsl/README.md
Labels: wgsl, editorial

#3490 wgsl concretiation: use T2 instead of T'
  wgsl/index.bs
Labels: wgsl, wgsl resolved, editorial

#3493 Describe allowance for viewport rounding
  spec/index.bs
Labels: editorial

#3484 Object labels are per-GPUObjectBase
  spec/index.bs
Labels: editorial

#3408 Matching rules for fragment shader output and color attachments
  spec/index.bs
Labels: editorial, needs-cts-issue

#3434 Rename maxColorAttachmentBytesPerPixel to *PerSample
  spec/index.bs
Labels: editorial

#3496 First pass over inline issues
  spec/index.bs
Labels: editorial

#3495 [editorial] Define "equal" for GPURenderPassLayout
  spec/index.bs
Labels: editorial

#3497 wgsl: indexing X by non-const-expr index requires X to be concrete
  wgsl/index.bs
Labels: wgsl, editorial

#3498 [editorial] Replace "super-luminant" with a more descriptive term
  spec/index.bs
Labels: editorial

#3491 [editorial] Semi-formalization of interface with WGSL
  spec/index.bs
Labels: editorial

#3494 wgsl: Define trunc, ceil, floor for infinities
  wgsl/index.bs
Labels: wgsl

#3507 Clarify behaviour of pack2x16float, quantizeToF16 for large inputs
  wgsl/index.bs
Labels: wgsl, editorial

#3509 [editorial] Clarify some spec around features
  spec/index.bs
Labels: editorial

#3510 [editorial] Describe textures and subresource accounting algorithms
  spec/index.bs
Labels: editorial

#3512 [editorial] Move texture extent algorithms to texture section
  spec/index.bs
Labels: editorial

#3499 Only allow defined GPUMapMode bits in mapAsync()
  spec/index.bs
Labels: tacit resolution queue, needs-cts-issue

#3500 Only allow defined GPUShaderStage bits in bind group layout entries
  spec/index.bs
Labels: tacit resolution queue, needs-cts-issue

#3505 Don't trail with empty BGLs in default pipeline layout
  spec/index.bs
Labels: tacit resolution queue

#3506 Don't throw exception when getBindGroupLayout index > maxBindGroups
  spec/index.bs
Labels: tacit resolution queue

#3518 wgsl: Remove address space names from "other keywords" list
  wgsl/index.bs
Labels: wgsl

#3515 [editorial] Misc trivial inline issue cleanup
  spec/index.bs
Labels: editorial

#3514 [editorial] Consolidate "Detailed Operations" issues into one issue
  spec/index.bs
Labels: for webgpu editors meeting, editorial

#3521 Fix the definition of "src-alpha-saturated"
  spec/index.bs
Labels: editorial

#3522 workgroupStorageUsed is sum of values, each rounded up to multiple of 16
  spec/index.bs
Labels: tacit resolution queue, needs-cts-issue

#3526 Remove stale/incorrect statement about inability to shadow builtins
  wgsl/index.bs
Labels: wgsl, editorial

#3529 Rename postfix_expression to component_or_swizzle_specifier
  wgsl/index.bs
  wgsl/wgsl.recursive.bs.include
Labels: wgsl, editorial

#3540 wgsl: Simplify note about runtime-sized array not being fixed-footprint
  wgsl/index.bs
Labels: wgsl, editorial

#3508 wgsl: Define "indeterminate value"
  wgsl/index.bs
Labels: wgsl

#3539 wgsl: Fix how we say concrete left shift must not overflow (if known …
  wgsl/index.bs
Labels: wgsl

#3422 wgsl: ban ptr-to-workgroup params to user-defined functions
  wgsl/index.bs
Labels: wgsl

#3553 Fix clamp definition
  wgsl/index.bs
Labels: wgsl

#3549 [editorial] Clarify nan/inf eval applies to all expressions
  wgsl/index.bs
Labels: wgsl, editorial

#3548 Generalize integer texture parameter requirements
  wgsl/index.bs
Labels: wgsl

#3547 Force concrete types unless all subexpressions are const-expressions
  wgsl/index.bs
Labels: wgsl

#3542 Add draft text/wgsl media type registration. WGSL uses UTF-8
  wgsl/index.bs
  wgsl/media-type-registration.txt
Labels: wgsl
