Repository gpuweb/gpuweb, pull requests merged in 2022-06, with the labels that each got.

#2974 wgsl: Use code tags for enable f16 code snippet.
  wgsl/index.bs
Labels: wgsl, editorial

#2918 Explicitly state the accuracy for clamp
  wgsl/index.bs
Labels: wgsl

#3000 Add interpolate, invariant to attribs that can be applied to struct m…
  wgsl/index.bs
Labels: wgsl resolved, editorial

#2919 Add reflection for container objects.
  spec/index.bs
Labels: for webgpu editors meeting

#2964 Clarify to interpret stencilClearValue as masked
  spec/index.bs
Labels: tacit resolution queue

#2950 Remove depth24unorm-stencil8
  spec/index.bs
Labels: tacit resolution queue

#2967 Use PredefinedColorSpace instead of GPUPredefinedColorSpace
  spec/index.bs
Labels: tacit resolution queue

#3011 Format internal slots consistently with IDL attributes
  explainer/index.bs
  spec/index.bs
Labels: editorial

#2985 Add maxColorAttachments missing from GPUSupportedLimits
  spec/index.bs
Labels: editorial

#2968 wgsl: Allow phony assignment of abstract numeric type
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#3016 Move builtin names to section headers.
  wgsl/index.bs
Labels: wgsl, editorial

#3018 Ensure the formats supporting multisampling must support rendering
  spec/index.bs
Labels: tacit resolution queue

#2754 Add WGSL grammar analyzer
  .gitignore
  wgsl/Makefile
  wgsl/analyze/Grammar.py
  wgsl/analyze/ObjectRegistry.py
  wgsl/analyze/lalr.py
  wgsl/analyze/test.py
  wgsl/analyze/test/ex417.json
  wgsl/analyze/test/ex442.json
  wgsl/analyze/test/firsts.json
  wgsl/analyze/test/star.json
Labels: wgsl

#3039 editorial: specify units for limits where relevant
  spec/index.bs
Labels: editorial

#3055 wgsl: Fix description of atomicCompareExchangeWeak
  wgsl/index.bs
Labels: bug, wgsl, editorial

#3090 Clarify color space section, add issue
  spec/index.bs
Labels: editorial

#2682 WGSL: Explain parameterized type rules more explicitly.
  wgsl/index.bs
Labels: wgsl

#2126 Update WGSL README: instructions about tree-sitter
  wgsl/README.md
Labels: wgsl

#3099 Add a note that WebGPU should be included in any high-power warnings
  spec/index.bs
Labels: editorial

#3098 "Fake" transfers of getMappedRange ArrayBuffers
  spec/index.bs
Labels: editorial

#3096 Update WGSL README, to discuss LALR(1) validation
  wgsl/Makefile
  wgsl/README.md
Labels: editorial

#3112 Fix abstract numeric cases for comparisons, length builtin
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#3110 Forbid pointer-to-workgroup param on user functions, when store type …
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#3116 [editorial] Make GPUCommandBuffer one-time-use
  design/CommandSubmission.md
  spec/index.bs
Labels: editorial

#3120 [editorial] Simplify "validating linear texture data"
  spec/index.bs
Labels: editorial
