Repository gpuweb/gpuweb, pull requests merged in 2022-12, with the labels that each got.

#3650 Reduce query set count limit to 4096
  spec/index.bs
Labels: tacit resolution queue, needs-cts-issue

#3626 Fix issues in pass end() validation
  spec/index.bs
Labels: tacit resolution queue

#3651 Check user IO equality only if the fragment stage is present.
  spec/index.bs
Labels: editorial

#3654 Link to WGSL definition of line breaks
  spec/index.bs
Labels: editorial

#3586 Add workgroupuniform load built-in and analysis
  wgsl/index.bs
Labels: wgsl, uniformity

#3661 Fix mapping state assertions in mapAsync
  spec/index.bs
Labels: editorial

#3666 text/wgsl media type registration is a normative part of the WGSL spec.
  wgsl/index.bs
Labels: wgsl, editorial

#3659 Add integer overloads for sign builtin function
  wgsl/index.bs
Labels: wgsl

#3622 [editorial] Remove note about non-meaningful result of scalar length
  wgsl/index.bs
Labels: editorial

#3664 Clarify powerPreference may also affect the power configuration on se…
  spec/index.bs
Labels: tacit resolution queue

#3665 begin pass: only generate error on incorrect state
  spec/index.bs
Labels: tacit resolution queue

#3693 Fix typo for vec2<u32> to vec2<f32> conversion
  wgsl/index.bs
Labels: wgsl, editorial

#3695 Fill out the compilationInfo() algorithm
  spec/index.bs
Labels: editorial

#3698 Reset [[pending_map]] to null in the RangeError case
  spec/index.bs
Labels: editorial

#3543 WGSL syntax styling upgrade with initial notation section
  wgsl/extract-grammar.py
  wgsl/index.bs
Labels: wgsl, editorial

#3706 Fix include
  wgsl/wgsl.recursive.bs.include
Labels: wgsl, editorial

#3523 Reject create*PipelineAsync on failure
  spec/index.bs
Labels: editorial, needs-cts-issue

#3632 Use task sources for device events and canvas texture expiry
  spec/index.bs
Labels: editorial, needs-cts-issue
