Repository gpuweb/gpuweb, pull requests merged in 2023-03, with the labels that each got.

#3887 Add TSPath.py XPath-style expressions for Treesitter nodes
  wgsl/Makefile
  wgsl/TSPath.py
  wgsl/wgsl_unit_tests.py
  wgsl/wgsl_unit_tests_enable.py
Labels: treesitter

#3892 wgsl: uniform buffers don't support stores
  wgsl/index.bs
Labels: wgsl, editorial

#3827 Update checks for dictionary members to use "exists"
  spec/index.bs
Labels: editorial

#3826 Change explainer status to "Draft Community Group Report"
  explainer/index.bs
Labels: editorial

#3821 Improve validation language around timestampWrites
  spec/index.bs
Labels: editorial

#3898 wgsl: weaken determinant error bounds
  wgsl/index.bs
Labels: wgsl

#3896 Rename notes column to description where appropriate
  wgsl/index.bs
Labels: wgsl, editorial

#3904 Ignore temporary file
  .gitignore
Labels: wgsl, editorial

#3899 Add ReturnIfAbrupt [=?=] on content-timeline validation
  spec/index.bs
Labels: editorial

#3903 [editorial] Assorted nits
  spec/index.bs
Labels: editorial

#3897 treesitter: Add more specific unit tests for template parsing
  wgsl/TSPath.py
  wgsl/wgsl_unit_tests_template.py
Labels: treesitter

#3890 Detabularize "Predeclared Types" list
  wgsl/index.bs
Labels: wgsl, editorial

#3907 Weaken asin accuracy rule for f32
  wgsl/index.bs
Labels: wgsl

#3910 [editorial] clarify host-shareable types
  wgsl/index.bs
Labels: wgsl, editorial

#3914 wgsl:editorial: Consistenly stye "Notes" as markers
  wgsl/index.bs
Labels: wgsl, editorial

#3918 Remove wrong restrictions on maxFragmentCombinedOutputResources value
  correspondence/index.bs
  spec/index.bs
Labels: editorial

#3713 Add diagnostic filtering; range diagnostics apply to control flow constructs and compound statements
  wgsl/index.bs
  wgsl/keywords
  wgsl/wgsl.recursive.bs.include
Labels: wgsl

#3920 Fix a "filterable" vs "blendable" reference mixup
  spec/index.bs
Labels: editorial

#3922 [editorial] Clearly distinguish texel copy footprints vs memory costs
  spec/index.bs
  spec/sections/copies.bs
Labels: editorial

#3929 [editorial] Always add vertical lines to data tables
  spec/index.bs
Labels: editorial

#3919 [editorial] Make a new section for Adapter Capability Guarantees
  spec/index.bs
Labels: editorial

#3924 [editorial] Rename variable_statement grammar
  wgsl/index.bs
  wgsl/wgsl.recursive.bs.include
Labels: wgsl, editorial

#3925 [editorial] Clarify memory locations
  wgsl/index.bs
Labels: wgsl, editorial

#3921 [editorial] Justify GPUStorageTextureAccess when it only has one value
  spec/index.bs
Labels: editorial

#3886 Enable directive takes a list of extensions.
  wgsl/index.bs
  wgsl/wgsl.recursive.bs.include
  wgsl/wgsl_unit_tests_enable.py
Labels: wgsl

#3834 Make rg11b10ufloat-renderable also allow resolving
  spec/index.bs
Labels: editorial

#3940 Adds maxFragmentCombinedOutputResources to GPUSupportedLimits.
  spec/index.bs
Labels: editorial

#3942 Describe the type of `GPUBindGroupLayout.[[descriptor]]`.
  spec/index.bs
Labels: editorial

#3933 Give algorithm for number of elements of runtime-sized array
  wgsl/index.bs
Labels: wgsl

#3947 Variable address space restrictions
  wgsl/index.bs
Labels: wgsl

#3945 Weaken min,max,clamp on denorm inputs
  wgsl/index.bs
Labels: wgsl

#3949 assignment evaluates from left to right
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#3943 Specify behavior of OffscreenCanvases
  spec/index.bs
Labels: editorial

#3957 Switch all GPUExtent/Origin accessors namespace
  spec/index.bs
  spec/sections/copies.bs
Labels: editorial

#3959 [editorial] Change redundant inter-stage variable validation to assertion
  spec/index.bs
Labels: editorial

#3969 Make frexp fract ranges explicit
  wgsl/index.bs
Labels: wgsl:builtins

#3965 editorial: Texel format and access mode are not context-dependent names
  wgsl/index.bs
Labels: bug, wgsl, editorial

#3958 Add accessors for GPUColor, define the sequence order
  spec/index.bs
Labels: editorial

#3955 Fix up expiry timing definitions
  spec/index.bs
Labels: editorial

#3930 Simplify timestampWrites API
  spec/index.bs
Labels: tacit resolution queue, needs-cts-issue

#3936 Expire GPUAdapter on the first successful requestDevice
  spec/index.bs
Labels: editorial

#3710 Make GPUPipelineError constructor `message` pseudo-optional
  spec/index.bs
Labels: editorial, needs-cts-issue

#3937 Specify behavior of onSubmittedWorkDone/mapAsync on device loss
  spec/index.bs
Labels: tacit resolution queue, needs-cts-issue

#3971 editorial: Define mathematical interval notation
  wgsl/index.bs
Labels: wgsl, editorial

#3972 editorial: Define and use "logical texel address"
  wgsl/index.bs
Labels: wgsl, editorial

#3976 GPUDeviceLostReason "unknown" instead of undefined
  spec/index.bs
Labels: editorial

#3977 Revert "Simplify timestampWrites API"
  spec/index.bs
Labels: editorial

#3956 Out of bounds access via reference is dynamic error
  wgsl/index.bs
Labels: wgsl

#3974 Clarify workgroup array size limit
  wgsl/index.bs
Labels: wgsl

#3988 frexp is well defined only for zero and normal numbers
  wgsl/index.bs
Labels: wgsl

#3960 Define GPUImageCopyExternalImage source size
  spec/index.bs
  spec/sections/copies.bs
Labels: editorial

#3997 Move all `<xmp>` to start on their own line
  tools/install-dependencies.sh
  wgsl/index.bs
Labels: editorial

#3990 Weaken asin & acos accuracy rule for f16
  wgsl/index.bs
Labels: wgsl

#3998 Fix when return value is ignored in a function call statement
  wgsl/index.bs
Labels: wgsl, editorial

#4002 Expose namespaces only in secure contexts, like interfaces.
  spec/index.bs
Labels: editorial, tacit resolution queue

#3983 alphaToCoverage comes from output 0, not target 0
  spec/index.bs
Labels: editorial

#3980 Require at least one attachment in GPURenderPipelineDescriptor
  spec/index.bs
Labels: editorial

#3981 Make aliased bindings an error
  spec/index.bs
Labels: editorial

#3975 Add more adapter limit guarantees
  spec/index.bs
Labels: editorial

#4001 [editorial] Suppress unused dfns using noexport
  spec/index.bs
Labels: editorial

#3984 Require a depth attachment if frag_depth builtin is used
  spec/index.bs
Labels: editorial

#4007 WASM Aid: Less queue capacity, don't account ASCII
  wgsl/scanner.cc
Labels: wgsl, editorial

#4011 Specify what happens if a dynamic error occrs
  wgsl/index.bs
Labels: wgsl

#4013 [editorial] Fill out texture types
  wgsl/index.bs
Labels: wgsl, editorial
