Repository gpuweb/gpuweb, pull requests merged in 2023-06, with the labels that each got.

#4160 [editorial] Fix GPUPipelineError constructor signature
  spec/index.bs
  tools/install-dependencies.sh
Labels: editorial

#4170 s/importTexture/importExternalTexture/
  explainer/index.bs
Labels: editorial

#4171 Update WGSL reference for WebGPU
  wgsl/index.bs
Labels: wgsl

#4075 Clarify language on storage texture capabilities
  wgsl/index.bs
Labels: wgsl, editorial

#4173 [editorial] GPUPipelineError: set slots instead of setting getters
  spec/index.bs
Labels: editorial

#4176 [editorial] Make Timelines normative
  spec/index.bs
Labels: editorial

#4164 [editorial] Overview edits
  wgsl/index.bs
Labels: wgsl, editorial

#4163 [editorial] Rework the built-in values table
  wgsl/index.bs
Labels: wgsl, editorial, wgsl:builtins

#4181 Remove expired attribute from JS example
  spec/index.bs
Labels: editorial

#4133 Allow reading storage buffers in vertex shaders (#4132).
  spec/index.bs
  wgsl/index.bs
Labels: editorial

#4188 Allow SharedArrayBuffer in writeBuffer/writeTexture with AllowSharedBufferSource
  spec/index.bs
Labels: proposal, tacit resolution candidate, needs-cts-issue

#4201 Fix Mermaid Diagram Issue and Upgrade GitHub Actions Workflows for Enhanced CI System
  .github/workflows/build-validate-publish.yml
  .github/workflows/preview-pull-request.yml
  .github/workflows/publish-TR-webgpu.yml
  .github/workflows/publish-TR-wgsl.yml
  spec/img/buffer-map-failure.mmd.svg
  spec/img/buffer-map-unmap.mmd.svg
  tools/check-repo-clean.sh
Labels: editorial

#4205 Tentatively disable mermaid check
  .github/workflows/build-validate-publish.yml
Labels: editorial
