Repository gpuweb/gpuweb, pull requests merged in 2023-11, with the labels that each got.

#4360 editorial: clip position definition links to clip space coords
  spec/index.bs
Labels: editorial

#4359 Coarsen timestamp value
  spec/index.bs
Labels: needs-cts-issue

#4364 Add note about undefined behaviors when copying from WebGL canvas
  spec/index.bs
Labels: editorial

#4358 Disallow requesting alignment limits that are ≥ 2**32
  spec/index.bs
Labels: proposal

#4379 Add more details to timing attack section
  spec/index.bs
Labels: editorial

#4380 Clarify comparison samplers can only be used on depth textures
  spec/index.bs
Labels: editorial

#4381 Actually explain what contagious invalidity is
  spec/index.bs
Labels: editorial

#2738 WGSL: Add dot4U8Packed and dot4I8Packed as new built-in functions
  wgsl/index.bs
Labels: wgsl, language extension

#4323 Remove restrictions on user-defined pointer parameters
  wgsl/index.bs
Labels: wgsl, language extension

#4391 [editorial] Apply component-wise to matrices
  wgsl/index.bs
Labels: wgsl, editorial

#4311 Add syntax sugar for dereferencing composites
  wgsl/index.bs
Labels: wgsl, language extension
