Repository gpuweb/gpuweb, pull requests merged in 2023-05, with the labels that each got.

#4058 Specify how errors from the WGSL spec are surfaced in the API
  spec/index.bs
  wgsl/index.bs
Labels: editorial

#4089 Add definitions to a bunch of dictionaries that were missing them
  spec/index.bs
Labels: editorial

#4095 Fix link for localizable text
  spec/index.bs
Labels: editorial

#4103 Validate types of fragment outputs
  spec/index.bs
Labels: editorial

#4102 webidl fix: Remove [EnforceRange] from GPUBuffer/Texture reflection attributes
  spec/index.bs
Labels: editorial

#4120 Fix more [EnforceRange]s
  spec/index.bs
Labels: editorial

#4060 Refine coordinate systems section
  spec/index.bs
Labels: editorial

#4117 More promise ordering guarantees
  spec/index.bs
Labels: editorial

#4136 Fix workload simulator for v1 spec
  samples/workload-simulator.html
Labels: editorial

#4139 Make section title plural
  wgsl/index.bs
Labels: wgsl, editorial

#4140 ULP is for non-equal, finite numbers
  wgsl/index.bs
Labels: wgsl

#4128 Define and use "clip space coordinates"
  spec/index.bs
  wgsl/index.bs
Labels: editorial

#4141 Define ULP for values outside the finite range
  wgsl/index.bs
Labels: wgsl, editorial

#4146 Use wgsl syntax highlighting
  spec/index.bs
  tools/install-dependencies.sh
  wgsl/index.bs
Labels: editorial

#4152 Add WGSL syntax highlighting to more examples
  wgsl/index.bs
Labels: wgsl

#4154 [editorial] Reorganize WGSL spec sections
  wgsl/index.bs
Labels: wgsl, editorial
