Repository gpuweb/gpuweb, pull requests merged in 2023-04, with the labels that each got.

#4016 [editorial] Fix section scoping
  wgsl/index.bs
Labels: wgsl, editorial

#4015 [editorial] Clarify uniformity expression categories
  wgsl/index.bs
Labels: wgsl, editorial

#3941 Add GPU.wgslLanguageExtensions to list the supported WGSL software extensions
  spec/index.bs
  wgsl/index.bs
Labels: tacit resolution queue

#4020 [editorial] Re-add splat constructors for vectors
  wgsl/index.bs
Labels: wgsl, editorial

#4029 Pin tree-sitter version more strictly
  wgsl/extract-grammar.py
Labels: wgsl, editorial

#3992 wgsl: unpack2x16snorm has 3 ULP error on some implementations
  wgsl/index.bs
Labels: wgsl

#4036 wgsl/analyzer/Grammar now understands Treesitter "REPEAT" node
  wgsl/analyze/Grammar.py
  wgsl/analyze/test.py
Labels: editorial

#4037 Raise an exception on an unknown grammar node type
  wgsl/analyze/Grammar.py
Labels: editorial

#4039 Fix description of workgroup_id
  wgsl/index.bs
Labels: editorial

#4035 Add helpful note to array sizing rules about override idents vs overr…
  wgsl/index.bs
Labels: wgsl, editorial

#4041 Clarify relation of global invocation ID to local invocation ID
  wgsl/index.bs
Labels: wgsl, editorial

#4045 [AllowShared] ArrayBuffer or [AllowShared] ArrayBufferView
  spec/index.bs
Labels: editorial

#4044 Remove maxFragmentCombinedOutputResources
  spec/index.bs
Labels: editorial

#4043 Allow alpha-to-coverage only if attachment 0 has alpha
  spec/index.bs
Labels: editorial

#4047 Update to bikeshed 3.11.21
  tools/install-dependencies.sh
Labels: editorial

#4048 Position inheritance clauses on separate lines for readability
  spec/index.bs
  spec/sections/copies.bs
Labels: editorial

#4053 Fix description of fragment/RasterizationPoint depth
  spec/index.bs
Labels: editorial

#4051 Stop raising errors during/after device loss
  spec/index.bs
Labels: for webgpu editors meeting, editorial, needs-cts-issue

#4054 Define standard sample patterns
  spec/index.bs
Labels: editorial

#4056 Revert "[AllowShared] ArrayBuffer or [AllowShared] ArrayBufferView"
  spec/index.bs
Labels: editorial

#3938 maxBindGroupsPlusVertexBuffers and unbinding
  spec/index.bs
Labels: for webgpu editors meeting, editorial, needs-cts-issue

#4059 Clarify element-by-element matrix construction
  wgsl/index.bs
Labels: editorial

#4061 Fix duplicated createBuffer validation, and tweak section levels
  spec/index.bs
Labels: editorial

#4067 [editorial] Fix broken link
  spec/index.bs
  wgsl/index.bs
Labels: editorial

#3114 Restore commas after final members of enums
  spec/index.bs
Labels: editorial

#4062 Clarify zero cases of occlusion queries
  spec/index.bs
Labels: editorial

#4063 Allow importExternalTexture from VideoFrame
  spec/index.bs
Labels: proposal, editorial

#4057 Account for dynamic offsets in binding aliasing validation
  spec/index.bs
Labels: editorial

#3979 Reland "Simplify timestampWrites API" with the rest of the spec updated
  spec/index.bs
Labels: editorial

#4070 Clean up more inline issues
  spec/index.bs
Labels: editorial
