Repository gpuweb/gpuweb, pull requests merged in 2023-12, with the labels that each got.

#4382 Clarify matching of pipeline constant identifiers.
  spec/index.bs
Labels: editorial

#4351 WGSL: Fix explanation of hyperbolic angles.
  wgsl/index.bs
Labels: wgsl, editorial, wgsl:functions

#4408 Reorganize WGSL tools
  .github/workflows/build-push-custom-image.yml
  spec/img/buffer-map-failure.mmd.svg
  spec/img/buffer-map-unmap.mmd.svg
  tools/custom-action/Dockerfile
  tools/custom-action/dependency-versions.sh
  wgsl/Makefile
  wgsl/img/operators_1.mmd.svg
  wgsl/img/uniformity_1.mmd.svg
  wgsl/img/uniformity_2.mmd.svg
  wgsl/img/uniformity_3.mmd.svg
  wgsl/img/uniformity_3b.mmd.svg
  wgsl/img/uniformity_4.mmd.svg
  wgsl/img/uniformity_5main.mmd.svg
  wgsl/img/uniformity_5scale.mmd.svg
  wgsl/tools/TSPath.py
  wgsl/tools/analyze/Grammar.py
  wgsl/tools/analyze/ObjectRegistry.py
  wgsl/tools/analyze/lalr.py
  wgsl/tools/analyze/test.py
  wgsl/tools/analyze/test/ex417.json
  wgsl/tools/analyze/test/ex442.json
  wgsl/tools/analyze/test/firsts.json
  wgsl/tools/analyze/test/star.json
  wgsl/tools/extract-grammar.py
  wgsl/tools/keywords
  wgsl/tools/scanner.cc
  wgsl/tools/wgsl_unit_tests.py
  wgsl/tools/wgsl_unit_tests_enable.py
  wgsl/tools/wgsl_unit_tests_equals.py
  wgsl/tools/wgsl_unit_tests_simple.py
  wgsl/tools/wgsl_unit_tests_template.py
Labels: wgsl, editorial

#4409 Hotfix: Explicitly invoke Puppeteer Install
  spec/img/buffer-map-failure.mmd.svg
  spec/img/buffer-map-unmap.mmd.svg
  tools/custom-action/Dockerfile
Labels: editorial

#4410 Hotfix1: Even more explicitly run install Puppeteer
  tools/custom-action/prepare.sh
Labels: editorial
