Repository gpuweb/gpuweb, pull requests merged in 2023-10, with the labels that each got.

#4314 Simplify makefile for WGSL for cross-platform runs
  wgsl/Makefile
Labels: wgsl, editorial

#4312 Remove restrictions on user-defined pointer parameters
  wgsl/index.bs
Labels: wgsl, language extension

#4322 Revert "Remove restrictions on user-defined pointer parameters (#4312)"
  wgsl/index.bs
Labels: wgsl

#4254 Add depthSlice to GPURenderPassColorAttachment for 3D texture
  spec/index.bs
Labels: proposal, needs-cts-issue

#4324 Add bitcast from abstractint to u32
  wgsl/index.bs
Labels: wgsl

#4327 editorial: fix typo in writeBuffer
  spec/index.bs
Labels: editorial

#4330 editorial: Improve "Note" headings
  spec/index.bs
Labels: editorial

#4328 Allow multiple compilation hints per entry point
  spec/index.bs
Labels: editorial, needs-cts-issue

#4343 Refactor `hints` record into `compilationHints` sequence
  spec/index.bs
Labels: editorial, needs-cts-issue

#4345 Fix nit in validating GPUDepthStencilState
  spec/index.bs
Labels: editorial

#4336 depthCompare is not required for depth attachments if not used
  spec/index.bs
Labels: needs-cts-issue

#4354 Remove unnecessary anchrors for access mode
  wgsl/index.bs
Labels: wgsl, editorial

#4331 Allow separate read-only state for depth and stencil aspects
  spec/index.bs
Labels: needs-cts-issue
