Repository gpuweb/gpuweb, pull requests merged in 2024-06, with the labels that each got.

#4679 Make `unmap()` device timeline validation explicit
  spec/index.bs
Labels: copyediting

#4627 Adjusts subgroup built-in name verbs to match atomics operations
  proposals/subgroups.md
Labels: wgsl

#4693 Clarify that using the standard sample patterns is mandatory
  spec/index.bs
Labels: copyediting

#4621 Add optional feature dual_source_blending
  spec/index.bs
  wgsl/index.bs
  wgsl/syntax.bnf
  wgsl/syntax/attribute.syntax.bs.include
  wgsl/syntax/blend_src_attr.syntax.bs.include
  wgsl/wgsl.recursive.bs.include
Labels: wgsl, wgsl resolved, api

#4710 Add missing `dual-source-blending` in `GPUFeatureName`
  spec/index.bs
Labels: copyediting

#4712 [Editorial] Fix a missing parenthesis
  spec/index.bs
Labels: copyediting

#4194 Guarantee that OOB writes to storage textures will be ignored
  wgsl/index.bs
Labels: wgsl

#4720 Extensions editorial: linking and syncing
  wgsl/index.bs
Labels: wgsl, copyediting

#4500 Add extended range
  spec/index.bs
Labels: needs-cts-issue, api
