Repository gpuweb/gpuweb, pull requests merged in 2024-05, with the labels that each got.

#4616 Add early evaluation errors for smoothstep
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#4578 wgsl: Reduce shader limits
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#4626 [non-normative] Drawing buffer can also be lazily cleared
  spec/index.bs
Labels: copyediting

#4640 Allow bitcast to flush to zero
  wgsl/index.bs
Labels: wgsl

#4608 Invalidate all command buffers passed to submit, whether the submit is valid or not.
  spec/index.bs
Labels: proposal

#4654 `indirectBuffer` should be added as `input` to the `usage scope`
  spec/index.bs
Labels: copyediting

#4625 Making valid, invalid, and expired regular properties
  spec/index.bs
Labels: copyediting, api

#4639 add first and either to interpolate
  wgsl/index.bs
  wgsl/tools/keywords
Labels: wgsl

#4670 Point to TC39 draft of source map spec instead of sourcemaps.info
  spec/index.bs
Labels: copyediting, api

#4673 Fix outdated [[internals]].[[state]] in diagrams
  spec/diagrams/buffer-map-failure.mmd
  spec/diagrams/buffer-map-unmap.mmd
  spec/img/buffer-map-failure.mmd.svg
  spec/img/buffer-map-unmap.mmd.svg
  spec/index.bs
  tools/check-repo-clean.sh
Labels: copyediting

#4671 Fixes for invoke-mermaid.sh and invoke-bikeshed.sh
  tools/check-repo-clean.sh
  tools/copy-if-different.sh
  tools/custom-action/entrypoint.sh
  tools/custom-action/prepare.sh
  tools/install-dependencies.sh
  tools/invoke-bikeshed.sh
  tools/invoke-mermaid.sh
  tools/populate-out.sh
Labels: github

#4652 Subgroups proposal: Consider subgroup_size used in compute stage uniform
  proposals/subgroups.md
Labels: wgsl

#4675 Spec orientation of each cube face, using a diagram
  spec/img/cubemap.svg
  spec/index.bs
Labels: copyediting

#4662 Replace asynchronous .requestAdapterInfo() with synchronous .info
  design/AdapterIdentifiers.md
  spec/index.bs
Labels: api

#4677 Allow compressed formats for 3D textures
  spec/index.bs
Labels: api resolved

#4678 Make sure the device is valid when creating a texture view
  spec/index.bs
Labels: copyediting

#4681 Add missing `multisample.count` validation
  spec/index.bs
Labels: copyediting, needs-cts-issue

#4588 Add optional feature `clip-distances`
  spec/index.bs
  wgsl/index.bs
Labels: wgsl, for webgpu editors meeting, api

#4684 [editorial] Fix var and value table footnote
  wgsl/index.bs
Labels: wgsl, copyediting
