Repository gpuweb/gpuweb, pull requests merged in 2024-11, with the labels that each got.

#4949 Fix default pipeline layout determination of sampling type for f32 textures
  spec/index.bs
Labels: bug, copyediting, api

#4927 Compatibility Mode: add vertex storage buffer and texture limits
  proposals/compatibility-mode.md
Labels: compat

#4838 Rename image copies -> texel copies
  spec/index.bs
  spec/sections/copies.bs
Labels: proposal, api

#4946 Allow empty bindGroupLayouts in GPUPipelineLayoutDescriptor
  spec/index.bs
Labels: needs-cts-issue, api resolved, api

#4951 Add 1-component vertex formats and unorm8x4-bgra
  spec/index.bs
Labels: api resolved, api

#4897 Allow `featureLevel: "compatibility"`, which does nothing
  spec/index.bs
Labels: proposal, compat, api resolved, api

#4903 Remove the [[destroy started]] state, go straight to 'lost'
  spec/index.bs
Labels: copyediting, api

#4809 Proposal: expose GPUAdapterInfo from GPUDevice
  spec/index.bs
Labels: needs-cts-issue, api resolved, api

#4958 Check bindGroupLayout entries are empty
  spec/index.bs
Labels: copyediting, api

#4960 wgsl: allow OffsetOfMember to be 0
  wgsl/index.bs
Labels: bug, wgsl

#4964 wgsl: fix typo
  wgsl/index.bs
Labels: copyediting

#4922 Add note about toneMapping mode in configure
  spec/index.bs
Labels: for webgpu editors meeting, needs-cts-issue, api

#4942 Add xrCompatible adapter flag
  spec/index.bs
Labels: api

#4974 wgsl: bool has size and alignment of 4 bytes
  wgsl/index.bs
Labels: wgsl

#4980 Clarify uniqueness of nearest enclosing diagnostic
  wgsl/index.bs
Labels: wgsl

#4912 Texel buffer proposal
  proposals/texel-buffers.md
Labels: proposal, wgsl, api

#4978 wgsl: @align(n) must divide required-align-of, for all structs
  wgsl/index.bs
Labels: wgsl

#4992 Fix host-shareable types note
  wgsl/index.bs
Labels: wgsl, copyediting

#4993 [M0 backport] Fix styling of adapter immutable properties (#4991)
  spec/index.bs
Labels: copyediting, api

#4998 Fix attribute validation
  spec/index.bs
Labels: copyediting, api

#5000 [M0 backport] Fix attribute validation (#4998)
  spec/index.bs
Labels: copyediting, api
