Repository gpuweb/gpuweb, pull requests merged in 2024-12, with the labels that each got.

#5015 Fix typos in refs to adapter capability guarantees section
  spec/index.bs
Labels: copyediting, api

#5017 [M0 backport] Fix typos in refs to adapter capability guarantees section (#5015)
  spec/index.bs
Labels: api

#5021 Add attributes and settings for consistent line endings
  .gitattributes
  .github/workflows/build-validate-publish.yml
  .github/workflows/preview-pull-request.yml
  .vscode/settings.json
  correspondence/img/.gitignore
  design/AdapterIdentifiers.md
  design/RejectedErrorHandling.md
  explainer/index.bs
  proposals/compatibility-mode.md
  tools/copy-if-different.sh
  tools/wgsl-meeting-helper
  wgsl/Makefile
  wgsl/diagrams/uniformity_1.mmd
  wgsl/media-type-registration.txt
  wgsl/tools/TSPath.py
  wgsl/tools/analyze/Grammar.py
  wgsl/tools/analyze/ObjectRegistry.py
  wgsl/tools/analyze/test.py
Labels: copyediting

#5027 Fix maxTextureDimension limits refs
  spec/index.bs
Labels: copyediting, api
