Repository gpuweb/gpuweb, pull requests merged in 2024-07, with the labels that each got.

#4730 Update viewport depth range validation
  spec/index.bs
Labels: copyediting, needs-cts-issue

#4732 wgsl: Fix range of atan: starts at -pi/2, not pi/2
  wgsl/index.bs
Labels: wgsl, copyediting

#4724 Clarify scope of pipeline creation
  wgsl/index.bs
Labels: wgsl resolved

#4740 Update VideoFrames to use display size
  spec/index.bs
  spec/sections/copies.bs
Labels: needs-cts-issue, api resolved

#4743 Point and line primitives must not have depth bias
  spec/index.bs
Labels: needs-cts-issue, api resolved

#4612 Push constant proposal
  proposals/push-constants.md
Labels: proposal, wgsl, api

#4757 Add missing "valid to use with" checks to `GPURenderPassDescriptor` Valid Usage
  spec/index.bs
Labels: copyediting

#4752 Suppress error generation in create*PipelineAsync, clarify async steps
  spec/index.bs
Labels: api resolved, api

#4760 Fix some language which ignores that limits get clamped to defaults
  spec/index.bs
Labels: copyediting

#4762 Require `module` to be "valid to use with" `device`
  spec/index.bs
Labels: copyediting, api

#4758 Clarify counting of case values for their maximum limit.
  wgsl/index.bs
Labels: wgsl

#4773 Note that leading zeros are forbidden because no octals.
  wgsl/index.bs
Labels: wgsl

#4767 Move overflow rules for concrete integers
  wgsl/index.bs
Labels: wgsl, copyediting

#4766 Clarify inherited-from allows flushing
  wgsl/index.bs
Labels: wgsl, copyediting

#4765 Clarify stage restrictions for IO attributes
  wgsl/index.bs
Labels: wgsl, copyediting

#4768 Add inverse channel transfer function
  wgsl/index.bs
Labels: wgsl, copyediting

#4790 If any vertex is OOB, the whole draw call may behave as OOB
  spec/index.bs
Labels: needs-cts-issue, api resolved, api

#4763 Add `texture-compression-bc-sliced-3d`
  spec/index.bs
Labels: needs-cts-issue, api resolved, api

#4789 Reject requestDevice() if the adapter has already been used
  spec/index.bs
Labels: needs-cts-issue, api resolved, api, potentially breaking

#4794 Remove mentions of multithreaded API
  spec/index.bs
  spec/sections/privacy-and-security.bs
Labels: copyediting

#4785 Change mapAsync to reject with AbortError on device loss
  spec/index.bs
Labels: needs-cts-issue, api resolved, api, potentially breaking

#4793 [editorial] Link to a definition for [=implementation-defined=]
  explainer/index.bs
  spec/index.bs
Labels: copyediting, api

#4797 [editorial] Make usage scope validation algorithmic
  spec/index.bs
Labels: copyediting, api

#4780 [editorial] Improve more language relating to limit defaults
  spec/index.bs
Labels: copyediting, api

#4799 [editorial] Simplify attachment usage validation
  spec/index.bs
Labels: copyediting, api

#4801 Clarify const-expression eval and type checking
  wgsl/index.bs
Labels: wgsl, wgsl resolved

#4771 Clarify textureSampleBias bias param
  wgsl/index.bs
Labels: wgsl, copyediting

#4792 Clarify array layer OOB for texture sampling
  wgsl/index.bs
Labels: wgsl
