Repository gpuweb/gpuweb, pull requests merged in 2024-08, with the labels that each got.

#4802 Add shader module creation validation for features
  spec/index.bs
Labels: copyediting, api

#4778 Add note that enabling features can have performance impact
  spec/index.bs
Labels: copyediting, api

#4796 [editorial] Add timelines to all attributes/slots, assorted editing
  spec/index.bs
Labels: copyediting, api

#4795 Add extra example for operations involving abstract numerics
  wgsl/index.bs
Labels: wgsl, copyediting

#4791 Fix rules about dual source blending in `validating GPUFragmentState`
  spec/index.bs
  wgsl/index.bs
Labels: api

#4823 wsgl: remove TODO about acos, asin accuracy for f16
  wgsl/index.bs
Labels: wgsl, copyediting

#4825 wsgl: clarify fp edge cases
  wgsl/index.bs
Labels: wgsl, copyediting

#4831 Clarify validation of storage texture texel-format and access modes
  wgsl/index.bs
Labels: wgsl

#4835 Better explain that you can't assign to a multi-letter swizzle
  wgsl/index.bs
Labels: wgsl, copyediting

#4820 subgroups: subgroupBroadcast 'id' parameter is const-expression
  proposals/subgroups.md
Labels: wgsl, enable extension

#4822 Add inclusive scan add and mul operations
  proposals/subgroups.md
Labels: enhancement, wgsl, enable extension

#4837 interstage-interpolation checks generate pipeline-creation errors, no…
  wgsl/index.bs
Labels: wgsl

#4781 Allow unknown limits to be requested with value `undefined`
  spec/index.bs
Labels: api resolved, api

#4783 Remove maxInterStageShaderComponents
  correspondence/index.bs
  spec/index.bs
Labels: needs-cts-issue, api resolved, api, potentially breaking

#4786 Generate a validation error on mapAsync early-reject
  spec/index.bs
Labels: proposal, needs-cts-issue, api resolved, api, potentially breaking

#4840 Remove GPUShaderModuleDescriptor.sourceMap
  spec/index.bs
Labels: api resolved, api

#4787 Change mapAsync to also early-reject if already mapped
  spec/index.bs
Labels: needs-cts-issue, api resolved, api, potentially breaking

#4788 Disable async operations after device destruction starts
  spec/index.bs
Labels: api
