Repository gpuweb/gpuweb, pull requests merged in 2024-09, with the labels that each got.

#4851 Add missing validation rule about |maxFragmentShaderInputVariables|
  spec/index.bs
Labels: bug, api resolved

#4746 Add usage to GPUTextureViewDescriptor
  spec/index.bs
Labels: needs-cts-issue, api resolved, api

#4855 Filling out the output merging section
  spec/index.bs
Labels: copyediting, api

#4858 Two's complement for AbstractInt and wording improvement for i32
  wgsl/index.bs
Labels: wgsl

#4860 [editorial] Fix fencepost error in maxBindGroupsPlusVertexBuffers validation
  spec/index.bs
Labels: copyediting, api

#4861 [editorial] Use `.[=list/size=]` instead of `.length`
  spec/index.bs
Labels: copyediting, api

#4863 [editorial] Make a definition for vertex format sizes
  spec/index.bs
Labels: copyediting, api

#4866 [editorial] remove assertion from "dot" syntax
  spec/index.bs
Labels: copyediting, api

#4862 [editorial] Use the word "return" instead of "stop"
  spec/index.bs
Labels: copyediting, api

#4865 [editorial] default GPUProgrammableStage.constants to {}
  spec/index.bs
Labels: copyediting, api

#4869 [editorial] Restore validation error accidentally removed in #4860
  spec/index.bs
Labels: copyediting, api

#4868 Add API surface for feature levels
  spec/index.bs
Labels: proposal, api resolved, api

#4873 Add `texture-compression-astc-sliced-3d`
  spec/index.bs
Labels: api resolved, api

#4872 Add note to warn on unusable viewFormats
  spec/index.bs
Labels: api resolved, api

#4864 Clarify that atomic `and` and `or` are bitwise operations, slightly restructure, and fix missing prepositions
  wgsl/index.bs
Labels: wgsl, copyediting

#4779 [push-constants] remove per-stage immediates open question
  proposals/push-constants.md
Labels: api

#4883 [editorial] Grammatical fix for some comments
  wgsl/index.bs
Labels: wgsl, copyediting

#4881 wgsl: Tweak wording of array constructor limit
  wgsl/index.bs
Labels: wgsl

#4884 Add derivatives to accuracy table
  wgsl/index.bs
Labels: wgsl

#4888 wgsl: clarify inherited-from accuracy applies after fp rules and shortcuts
  wgsl/index.bs
Labels: wgsl

#4882 Address the remaining TODO in the WGSL spec for sample footprint
  wgsl/index.bs
Labels: wgsl

#4874 Allow only strings in `featureLevel`
  spec/index.bs
Labels: proposal, api

#4899 Add GPUCanvasContext getConfiguration() method
  spec/index.bs
Labels: api resolved, api

#4902 Add [[lastPresentedImage]] as fallback for canvas image
  spec/index.bs
Labels: api resolved, api
