Repository gpuweb/gpuweb, pull requests merged in 2024-04, with the labels that each got.

#4366 Specify copy rules for different canvas contexts
  spec/index.bs
  spec/sections/copies.bs
Labels: editorial

#4559 Move Attribute Values out of Enumerants
  wgsl/index.bs
  wgsl/syntax.bnf
  wgsl/syntax/attribute.syntax.bs.include
  wgsl/syntax/builtin_value_name.syntax.bs.include
  wgsl/syntax/interpolate_sampling_name.syntax.bs.include
  wgsl/syntax/interpolate_type_name.syntax.bs.include
  wgsl/wgsl.recursive.bs.include
Labels: wgsl

#4476 Clarify behavior of out-of-gamut canvas
  spec/index.bs
Labels: editorial

#4564 Compat: disallow textureLoad with depth textures
  proposals/compatibility-mode.md
Labels: compat

#4571 [editorial] Update old incorrectly styled timeline boxes, clarify timeline examples
  spec/index.bs
Labels: editorial

#4570 [editorial] Tweak "requirements" style for clarity, in a few instances
  spec/index.bs
Labels: editorial

#4580 Remove resolved TODOs
  spec/index.bs
Labels: editorial

#4586 Clarify when canvas resize algorithm applies
  spec/index.bs
Labels: editorial, needs-cts-issue

#4593 Require that every submitted command buffer must be unique
  spec/index.bs
Labels: tacit resolution queue

#4554 Better Specialize Syntax, Fix Typos, and Improve Grammar Validation Script
  wgsl/index.bs
  wgsl/syntax.bnf
  wgsl/syntax/align_attr.syntax.bs.include
  wgsl/syntax/attrib_end.syntax.bs.include
  wgsl/syntax/attribute.syntax.bs.include
  wgsl/syntax/binding_attr.syntax.bs.include
  wgsl/syntax/builtin_attr.syntax.bs.include
  wgsl/syntax/compute_attr.syntax.bs.include
  wgsl/syntax/const_attr.syntax.bs.include
  wgsl/syntax/diagnostic_attr.syntax.bs.include
  wgsl/syntax/diagnostic_control.syntax.bs.include
  wgsl/syntax/fragment_attr.syntax.bs.include
  wgsl/syntax/group_attr.syntax.bs.include
  wgsl/syntax/id_attr.syntax.bs.include
  wgsl/syntax/interpolate_attr.syntax.bs.include
  wgsl/syntax/invariant_attr.syntax.bs.include
  wgsl/syntax/location_attr.syntax.bs.include
  wgsl/syntax/must_use_attr.syntax.bs.include
  wgsl/syntax/severity_control_name.syntax.bs.include
  wgsl/syntax/size_attr.syntax.bs.include
  wgsl/syntax/vertex_attr.syntax.bs.include
  wgsl/syntax/workgroup_size_attr.syntax.bs.include
  wgsl/tools/extract-grammar.py
  wgsl/wgsl.recursive.bs.include
Labels: wgsl, copyediting

#4563 [editorial] Clarify ldexp overloads
  wgsl/index.bs
Labels: wgsl, copyediting
