Repository gpuweb/gpuweb, pull requests merged in 2025-01, with the labels that each got.

#5040 Add placeholder Deadlines to specs as a workaround for Bikeshed problem
  spec/index.bs
  wgsl/index.bs
Labels: wgsl, copyediting, api

#5038 Move Correspondence Reference from LD to UD, to fix CSS
  correspondence/index.bs
Labels: copyediting, api

#5039 Correspondence: document Vulkan's `maxFragmentCombinedOutputResources`
  correspondence/index.bs
Labels: copyediting, api

#4963 Add subgroups feature
  spec/index.bs
  wgsl/index.bs
Labels: wgsl, api

#5046 Fix tags that cause build errors in the WGSL spec
  wgsl/index.bs
Labels: copyediting

#5047 Fix incorrect end tags
  spec/index.bs
Labels: copyediting, api

#5048 wgsl: further clarify override expr evaluation only if in the shader
  wgsl/index.bs
Labels: wgsl, copyediting

#5034 Compat: update new limits proposal
  proposals/compatibility-mode.md
Labels: compat

#4940 Add a proposal for sized-binding-arrays
  proposals/sized-binding-arrays.md
Labels: api

#5053 Compat: disallow multisampled integer textures
  proposals/compatibility-mode.md
Labels: compat, api

#5052 Compat: disallow multisampled f16/f32 textures
  proposals/compatibility-mode.md
Labels: api

#5056 [editorial] Compat: Move IDL for textureBindingViewDimension into the appropriate section
  proposals/compatibility-mode.md
Labels: copyediting, api

#5025 Loosen viewport validation requirements
  correspondence/index.bs
  spec/index.bs
Labels: api resolved, api
