Repository gpuweb/gpuweb, pull requests merged in 2025-09, with the labels that each got.

#5302 Regenerate diagrams with latest image
  spec/img/buffer-map-failure.mmd.svg
  spec/img/buffer-map-unmap.mmd.svg
Labels: copyediting, github

#5304 [editorial] Compat: add rigor to texture call validation
  spec/index.bs
Labels: copyediting, api

#5319 Match WGSL syntax and clean open questions
  proposals/texture-component-swizzle.md
Labels: api resolved, api

#5309 Improve docs around getConfiguration and feature detection in general
  spec/index.bs
Labels: copyediting, api

#5310 [bugfix] Fix copyExternalImageToTexture steps to handle *-srgb formats
  spec/index.bs
Labels: bug, copyediting, api
