Repository gpuweb/gpuweb, pull requests merged in 2025-06, with the labels that each got.

#5213 Auto-enable `rg11b10ufloat-renderable` with `texture-formats-tier1`
  spec/index.bs
Labels: api resolved, api

#5219 subgroups: Clarify subgroup size is a power of two
  wgsl/index.bs
Labels: wgsl

#5226 Add optional feature `texture-formats-tier2`
  spec/index.bs
Labels: texture-capabilities, api
