Repository gpuweb/gpuweb, pull requests merged in 2025-10, with the labels that each got.

#4597 [non-normative] Explain -srgb formats are not color managed/tagged
  spec/index.bs
Labels: copyediting, api

#5333 copyExternalImageToTexture: allow all unorm/unorm-srgb/float/ufloat textures
  spec/index.bs
Labels: api resolved, api

#5332 Proposal to add subgroup_id built-in value
  proposals/subgroup-id.md
Labels: proposal, wgsl
