Repository gpuweb/gpuweb, pull requests merged in 2025-05, with the labels that each got.

#5173 [immediates proposal] Rename to immediateSize and maxImmediateSize
  proposals/push-constants.md
Labels: proposal, api

#5174 [binding array proposal] Choose a clearer name for binding array size, in BGL
  proposals/sized-binding-arrays.md
Labels: proposal, api

#5194 In "Limits", remove duplicated note.
  spec/index.bs
Labels: copyediting, api

#5160 Add optional feature `texture-formats-tier1`
  spec/index.bs
  wgsl/index.bs
Labels: proposal, api resolved, api

#5193 Add GPUBuffer in GPUBindingResource
  spec/index.bs
Labels: api resolved, api

#5202 Add [AllowShared] to setBindGroup
  spec/index.bs
Labels: needs-cts-issue, api
