Repository gpuweb/gpuweb, pull requests merged in 2025-03, with the labels that each got.

#5091 wgsl: Remove binding_array from reserved keywords
  wgsl/tools/keywords
  wgsl/wgsl.reserved.bs.include
Labels: wgsl

#5099 Move GPUAdapter isFallbackAdapter attribute to GPUAdapterInfo
  spec/index.bs
Labels: api resolved, api

#5079 Allow using a texture view for an externalTexture binding
  spec/index.bs
Labels: proposal, api resolved, api

#5114 mapAsync always AbortErrors after device loss
  spec/index.bs
Labels: api resolved, api

#5113 Synchronously validate size % 4 == 0 on mappedAtCreation
  spec/index.bs
Labels: api resolved, api

#5120 workgroupUniformLoad: returns concrete constructible type
  wgsl/index.bs
Labels: bug

#5104 Compat: Un-lower maxStorageBuffersPerShaderStage
  proposals/compatibility-mode.md
Labels: proposal, compat, api

#5131 Compat: Raise maxStorageTexturesInFragment and maxStorageBuffersInFragmentStage to 4
  proposals/compatibility-mode.md
Labels: api resolved, api
