Repository gpuweb/gpuweb, pull requests merged in 2025-04, with the labels that each got.

#5136 [editorial] Fix note in subgroupInclusiveAdd
  wgsl/index.bs
Labels: wgsl, copyediting

#5147 Add "core-features-and-limits" to spec
  spec/index.bs
Labels: compat, api resolved, api

#5166 Add guidance to build the image with devcontainer
  .devcontainer/devcontainer.json
Labels: copyediting

#5163 Make quotes part of the link for consistency
  wgsl/index.bs
Labels: wgsl, copyediting

#5169 Specify that ASTC Sliced 3D feature requires ASTC feature
  spec/index.bs
Labels: api resolved, api

#5007 Subgroups: add note for subgroupMinSize
  proposals/subgroups.md
Labels: api

#5170 Add FSA to LICENSE, and inline license text
  CONTRIBUTING.md
  LICENSE.md
  README.md
Labels: meta

#5182 Copy license to out/ for gh-pages
  tools/populate-out.sh
Labels: github

#5184 BC does not guarantee Sliced 3D
  spec/index.bs
Labels: api resolved

#5183 Fix custom dark mode styles for Bikeshed switcher
  spec/index.bs
Labels: copyediting, api
